version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - EmaSuriano
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.8.0
    - 7.0.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 3.0.3
    - 3.0.4
    - 3.1.1
    - 3.1.2
    - 3.2.1
  - dependency-name: "@percy/cypress"
    versions:
    - 2.3.4
    - 3.0.0
  - dependency-name: grommet
    versions:
    - 2.16.2
    - 2.16.3
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.9.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
