language: node_js

node_js:
  - stable

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  yarn: true

install:
  - yarn --frozen-lockfile --ignore-engines

script:
  - yarn test:ci
  - yarn build
